export const LIST_GETALL = "LIST_GETALL";
export const SET_PRODUCTS_TO_STATE = "SET_PRODUCTS_TO_STATE";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
